# Workflow GitHub pour les applications Python

name: Python Application CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Étape de vérification du code source
      - name: Checkout repository
        uses: actions/checkout@v4

      # Configuration de Python
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      # Installation des dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Lint avec flake8 pour vérifier le style de code
      - name: Lint with flake8
        run: |
          # Affiche les erreurs de syntaxe ou les noms indéfinis
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # Utilise exit-zero pour traiter les erreurs comme des avertissements
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      # Exécution des tests avec pytest
      - name: Run tests with pytest
        run: |
          pytest --disable-warnings
